/* Subtraindo DATAS */

DECLARE @DT_ANO DATETIME
      , @DT_COMPETENCIA VARCHAR (20) 
	  , @PARAMETRO INT

SET @DT_COMPETENCIA = GETDATE()
SET @DT_ANO = CONVERT(DATETIME,@DT_COMPETENCIA)
SET @PARAMETRO = -2

SELECT GETDATE() AS DATA_ATUAL
     , DATEADD (m, @PARAMETRO , @DT_ANO ) AS RESULT1
     , CONVERT(VARCHAR(20),DATEADD (m, @PARAMETRO , @DT_ANO ),112) AS RESULT2
	 , LEFT(CONVERT(VARCHAR(20),DATEADD (m, @PARAMETRO , @DT_ANO ),112),6) AS RESULT3
