/* Subtraindo DATAS */

DECLARE @DT_ANO DATETIME
      , @DT_COMPETENCIA VARCHAR (20) 
	  , @PARAMETRO INT

SET @DT_COMPETENCIA = GETDATE()
SET @DT_ANO = CONVERT(DATETIME,@DT_COMPETENCIA)
SET @PARAMETRO = -2

SELECT GETDATE() AS DATA_ATUAL
     , DATEADD (m, @PARAMETRO , @DT_ANO ) AS RESULT1
     , CONVERT(VARCHAR(20),DATEADD (m, @PARAMETRO , @DT_ANO ),112) AS RESULT2
	 , LEFT(CONVERT(VARCHAR(20),DATEADD (m, @PARAMETRO , @DT_ANO ),112),6) AS RESULT3



DECLARE @DATA1 DATETIME = '01/01/2019'
      , @DATA2 DATETIME = '31/12/2017'

SELECT @DATA2, @DATA1

SELECT DATEDIFF(year,        @DATA2, @DATA1) AS ANOS
SELECT DATEDIFF(quarter,     @DATA2, @DATA1) AS TRIMESTRES
SELECT DATEDIFF(month,       @DATA2, @DATA1) AS MESES
SELECT DATEDIFF(dayofyear,   @DATA2, @DATA1) AS DIAS_DO_ANO
SELECT DATEDIFF(day,         @DATA2, @DATA1) AS DIAS
SELECT DATEDIFF(week,        @DATA2, @DATA1) AS SEMANAS
SELECT DATEDIFF(hour,        @DATA2, @DATA1) AS HORAS  ;
SELECT DATEDIFF(minute,      @DATA2, @DATA1) AS MINUTOS;
SELECT DATEDIFF(second,      @DATA2, @DATA1) AS SEGUNDOS ;
/* SELECT DATEDIFF(millisecond, @DATA2, @DATA1) AS MILISEGUNDO; */
